SELECT
    U.ID,
    U.FIRST_NAME,
    U.LAST_NAME,
    C.ID AS COMPANY_ID,
    C.NAME AS COMPANY_NAME,
    R.NAME AS USER_TYPE
FROM
    USERS_USER U
    LEFT JOIN COMPANIES_CUSTOMERCOMPANY C ON U.COMPANY_ID = C.ID
    LEFT JOIN USERS_USER_ROLES UR ON U.ID = UR.USER_ID
    LEFT JOIN ROLES_ROLE R ON UR.ROLE_ID = R.ID